name: "Initialize Beat Saber Development Environment"
description: "A GitHub Action to initialize a Beat Saber modding environment"
author: "BeatForge"

branding:
  icon: "package"
  color: "red"

inputs:
  token:
    description: "The GitHub token to use for downloading the modding environment"
    default: "${{ github.token }}"
    required: false
  version:
    description: "The Beat Saber version to use. Optional if 'ref' is provided or can be inferred from manifest.json."
    required: false
  ref:
    description: "The Git reference to download (branch, tag, or commit SHA). Overrides the 'version' input if provided."
    required: false
  manifest:
    description: "The path to the manifest.json file to infer version if 'version' is not specified"
    required: false
  path:
    description: "The location to install the modding environment to"
    required: false
    default: "./Refs"
  host:
    description: "The GitHub host to use"
    required: false
    default: "github.com"
  repo:
    description: "The repository to use (format: owner/repo)"
    default: "beat-forge/beatsaber-stripped"
    required: false

runs:
  using: "node20"
  main: "dist/index.js"
